AgroTech1.4/Controllers/NodesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AgroTech1._4.Models;

namespace AgroTech1._4.Controllers
{
    public class NodesController : Controller
    {
        private eMES_AgroTechEntities db = new eMES_AgroTechEntities();

        // GET: Nodes
        public ActionResult IndexNodes()
        {
            return View(db.tblATNodes.ToList());
        }

        // GET: Nodes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Nodes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "node_id,node_name,node_type")] tblATNode tblATNode)
        {
            if (ModelState.IsValid)
            {
                db.tblATNodes.Add(tblATNode);
                db.SaveChanges();
                return RedirectToAction("IndexNodes");
            }

            return View(tblATNode);
        }

        // GET: Nodes/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblATNode tblATNode = db.tblATNodes.Find(id);
            if (tblATNode == null)
            {
                return HttpNotFound();
            }
            return View(tblATNode);
        }

        // POST: Nodes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "node_id,node_name,node_type")] tblATNode tblATNode)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblATNode).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("IndexNodes");
            }
            return View(tblATNode);
        }

        // GET: Nodes/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblATNode tblATNode = db.tblATNodes.Find(id);
            if (tblATNode == null)
            {
                return HttpNotFound();
            }
            return View(tblATNode);
        }

        // POST: Nodes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            tblATNode tblATNode = db.tblATNodes.Find(id);
            db.tblATNodes.Remove(tblATNode);
            db.SaveChanges();
            return RedirectToAction("IndexNodes");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AgroTech1.4/Controllers/NodesSensorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AgroTech1._4.Models;

namespace AgroTech1._4.Controllers
{
    public class NodesSensorsController : Controller
    {
        private eMES_AgroTechEntities db = new eMES_AgroTechEntities();

        // GET: NodesSensors
        public ActionResult IndexNodesSensors()
        {
            return View(db.viATNodesSensors.ToList());
        }

    }  
}

AgroTech1.4/Views/Nodes/Create.cshtml
@model AgroTech1._4.Models.tblATNode

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
  
<div class="container">
    <div class="d-flex justify-content-center">
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <div class="control-label">
                    Node name
                </div>
                <div>
                    @Html.EditorFor(model => model.node_name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.node_name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="control-label">
                    Node type
                </div>
                <div>
                    @Html.EditorFor(model => model.node_type, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.node_type, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div>
                    <input type="submit" value="Create" class="btn btn-outline-success btn-block" />
                </div>
                <hr />
                <div>
                    @Html.ActionLink("Back to List", "IndexNodes", null, new { @class = "btn btn-outline-info btn-block" })
                </div>
            </div>
        </div>
    </div>
</div>
        }

AgroTech1.4/Views/Nodes/Delete.cshtml
@model AgroTech1._4.Models.tblATNode

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <div class="control-label">
                Node name
            </div>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.node_name)
        </dd>

        <dt>
            <div class="control-label">
                Node type
            </div>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.node_type)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-outline-danger" /> 
        <hr />
        <div class="col-md-offset-2 col-md-10">
            @Html.ActionLink("Back to List", "IndexNodes")
        </div>
    </div>
    }
</div>

AgroTech1.4/Views/Nodes/Edit.cshtml
@model AgroTech1._4.Models.tblATNode

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
<div class="container">
    <div class="d-flex justify-content-center">
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.node_id)

            <div class="form-group">
                <div class="control-label">
                    Node name
                </div>
                <div>
                    @Html.EditorFor(model => model.node_name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.node_name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="control-label">
                    Node type
                </div>
                <div>
                    @Html.EditorFor(model => model.node_type, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.node_type, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div>
                    <input type="submit" value="Save" class="btn btn-outline-success btn-block" />
                </div>
                <hr />
                <div>
                    @Html.ActionLink("Back to List", "IndexNodes", null, new { @class = "btn btn-outline-info btn-block" })
                </div>
            </div>
        </div>
    </div>
</div>
}

 

AgroTech1.4/Views/Nodes/IndexNodes.cshtml
@model IEnumerable<AgroTech1._4.Models.tblATNode>

@{
    ViewBag.Title = "Nodes";
}

<h2>Nodes</h2>

<p>
    @Html.ActionLink("New", "Create", null, new { @class = "btn btn-outline-success" })
</p>
<table class="table">
    <tr>
        <th>
            Node name
        </th>
        <th>
            Node type
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.node_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.node_type)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.node_id }, new { @class = "btn btn-outline-info" }) 
            @Html.ActionLink("Delete", "Delete", new { id=item.node_id }, new { @class = "btn btn-outline-danger" })
        </td>
    </tr>
}

</table>

<p>
    @Html.ActionLink("Add node sensor connection", "IndexNodesSensors", "NodesSensors")
    </p>