AgroTech1.4/Controllers/PlantsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AgroTech1._4.Models;

namespace AgroTech1._4.Controllers
{
    public class PlantsController : Controller
    {
        private eMES_AgroTechEntities db = new eMES_AgroTechEntities();

        // GET: Plants
        public ActionResult IndexPlants()
        {
            var tblATPlants = db.tblATPlants.Include(t => t.tblATNode);
            return View(tblATPlants.ToList());
        }

        // GET: Plants/Create
        public ActionResult Create()
        {
            ViewBag.node_id = new SelectList(db.tblATNodes, "node_id", "node_name");
            return View();
        }

        // POST: Plants/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "plant_id,plant_name,node_id,details")] tblATPlant tblATPlant, HttpPostedFileBase img)
        {
            if (img != null)
            {
                String FileExt = Path.GetExtension(img.FileName).ToUpper();
                if (FileExt == ".JPG" || FileExt == ".JPEG" || FileExt == ".PNG")
                {

                    byte[] bytes;

                    using (BinaryReader br = new BinaryReader(img.InputStream))
                    {
                        bytes = br.ReadBytes(img.ContentLength);
                    }

                    tblATPlant.img = bytes;

                    if (ModelState.IsValid)
                    {

                        db.tblATPlants.Add(tblATPlant);
                        db.SaveChanges();
                        return RedirectToAction("IndexPlants");
                    }

                    ViewBag.node_id = new SelectList(db.tblATNodes, "node_id", "node_name", tblATPlant.node_id);
                    return View(tblATPlant);
                }


                else
                {
                    ViewBag.FileStatus = "Invalid file format.";
                    ViewBag.node_id = new SelectList(db.tblATNodes, "node_id", "node_name");
                    return View();
                }
            }
            else
            {
                if (ModelState.IsValid)
                {

                    db.tblATPlants.Add(tblATPlant);
                    db.SaveChanges();
                    return RedirectToAction("IndexPlants");
                }

                ViewBag.node_id = new SelectList(db.tblATNodes, "node_id", "node_name", tblATPlant.node_id);
                return View(tblATPlant);
            }
        }

        // GET: Plants/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblATPlant tblATPlant = db.tblATPlants.Find(id);
            if (tblATPlant == null)
            {
                return HttpNotFound();
            }
            ViewBag.node_id = new SelectList(db.tblATNodes, "node_id", "node_name", tblATPlant.node_id);
            return View(tblATPlant);
        }

        // POST: Plants/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "plant_id,plant_name,node_id,details")] tblATPlant tblATPlant, HttpPostedFileBase img)
        {

            if (img != null)
            {
                String FileExt = Path.GetExtension(img.FileName).ToUpper();
                if (FileExt == ".JPG" || FileExt == ".JPEG" || FileExt == ".PNG")
                {

                    byte[] bytes;

                    using (BinaryReader br = new BinaryReader(img.InputStream))
                    {
                        bytes = br.ReadBytes(img.ContentLength);
                    }

                    tblATPlant.img = bytes;

                    if (ModelState.IsValid)
                    {

                        db.Entry(tblATPlant).State = EntityState.Modified;
                        db.SaveChanges();
                        return RedirectToAction("IndexPlants");
                    }

                    ViewBag.node_id = new SelectList(db.tblATNodes, "node_id", "node_name", tblATPlant.node_id);
                    return View(tblATPlant);
                }


                else
                {
                    ViewBag.FileStatus = "Invalid file format.";
                    ViewBag.node_id = new SelectList(db.tblATNodes, "node_id", "node_name");
                    return View();
                }
            }
            else
            {
               
                if (ModelState.IsValid)
                {
                    db.Entry(tblATPlant).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("IndexPlants");
                }

                ViewBag.node_id = new SelectList(db.tblATNodes, "node_id", "node_name", tblATPlant.node_id);
                return View(tblATPlant);
            }
        }

        // GET: Plants/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblATPlant tblATPlant = db.tblATPlants.Find(id);
            if (tblATPlant == null)
            {
                return HttpNotFound();
            }
            return View(tblATPlant);
        }

        // POST: Plants/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            tblATPlant tblATPlant = db.tblATPlants.Find(id);
            db.tblATPlants.Remove(tblATPlant);
            db.SaveChanges();
            return RedirectToAction("IndexPlants");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AgroTech1.4/Views/Plants/Create.cshtml
@model AgroTech1._4.Models.tblATPlant
@{
    ViewBag.Title = "Create Plant";
}
<h2>Create</h2>

@using (Html.BeginForm("Create", "Plants", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="container">
    <div class="d-flex justify-content-center">
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <div class="control-label">
                    Plant name
                </div>
                <div>
                    @Html.EditorFor(model => model.plant_name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.plant_name, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="control-label">
                    Node id
                </div>
                <div >
                    @Html.DropDownList("node_id", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.node_id, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="control-label">
                    Image
                </div>
                <div>

                    @Html.TextBoxFor(m => m.img, new { type = "file", @class = "btn btn-info" })
                    @Html.ValidationMessageFor(model => model.img, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="control-label">
                    Details
                </div>
                <div>
                    @Html.EditorFor(model => model.details, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.details, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div>
                    <input type="submit" value="Create" class="btn btn-outline-success btn-block" />
                </div>
                <hr />
                <div>
                    @Html.ActionLink("Back to List", "IndexPlants", null, new { @class = "btn btn-outline-info btn-block" })
                </div>
            </div>
        </div>
    </div>
</div>
}

AgroTech1.4/Views/Plants/Delete.cshtml
@model AgroTech1._4.Models.tblATPlant

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <div class="control-label">
                Plant name
            </div>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.plant_name)
        </dd>

        <dt>
            <div class="control-label">
                Image
            </div>
        </dt>
            @if (Model.img != null)
            {
                var base64 = Convert.ToBase64String(Model.img);
                var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                <img src="@imgSrc" class="img-responsive" style="height: auto; width: 200px; max-height: 200px" />
            }
            else
            {
                <img src="~/Content/img/plant.png" class="img-responsive" style="height: auto; width: 200px; max-height: 200px" />
            }
        </dd>

        <dt>
            <div class="control-label">
                Details
            </div>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.details)
        </dd>

        <dt>
            <div class="control-label">
                Node name
            </div>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblATNode.node_name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-outline-danger" /> 
        <hr />
        <div class="col-md-offset-2 col-md-10">
            @Html.ActionLink("Back to List", "IndexPlants")
        </div>
    </div>
    }
</div>

AgroTech1.4/Views/Plants/Edit.cshtml
@model AgroTech1._4.Models.tblATPlant

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Plants", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="container">
        <div class="d-flex justify-content-center">
            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.plant_id)

                <div class="form-group">
                    <div class="control-label">
                        Plant name
                    </div>
                    <div>
                        @Html.EditorFor(model => model.plant_name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.plant_name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="control-label">
                        Node id
                    </div>
                    <div>
                        @Html.DropDownList("node_id", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.node_id, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="control-label">
                        Image
                    </div>
                    <div class="text-center">
                        @if (Model.img != null)
                        {
                            var base64 = Convert.ToBase64String(Model.img);
                            var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                            <img src="@imgSrc" class="img-responsive" style="height: auto; width: 200px; max-height: 200px" />
                        }
                        else
                        {
                            <img src="~/Content/img/plant.png" class="img-responsive" style="height: auto; width: 200px; max-height: 200px" />
                        }
                    </div>
                    <br />
                    <div>
                        @Html.TextBoxFor(m => m.img, new { type = "file", @class = "btn btn-info", Value=Model.img})
                        @Html.ValidationMessageFor(model => model.img, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="control-label">
                        Details
                    </div>
                    <div>
                        @Html.EditorFor(model => model.details, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.details, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div>
                        <input type="submit" value="Save" class="btn btn-outline-success btn-block" />
                    </div>
                    <hr />
                    <div>
                        @Html.ActionLink("Back to List", "IndexPlants", null, new { @class = "btn btn-outline-info btn-block" })
                    </div>
                </div>
            </div>
        </div>
    </div>
}

AgroTech1.4/Views/Plants/IndexPlants.cshtml
@model IEnumerable<AgroTech1._4.Models.tblATPlant>

@{
    ViewBag.Title = "Plants";
}

<h2>Plants</h2>

<p>
    @Html.ActionLink("New", "Create", null, new { @class = "btn btn-outline-success" })
</p>
<table class="table" style="height: 100%">
    <tr>
        <th>
            Plant name
        </th>
        <th>
            Image
        </th>
        <th>
            Details
        </th>
        <th>
            Node name
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td class="align-middle">
                @Html.DisplayFor(modelItem => item.plant_name)
            </td>
            <td class="align-middle">
                @if (item.img != null)
                {
                    var base64 = Convert.ToBase64String(item.img);
                    var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                    <img src="@imgSrc" class="img-responsive"  style="height: auto; width: 200px; max-height: 200px" />
                }
                else{ 
                    <img src="~/Content/img/plant.png" class="img-responsive"  style="height: auto; width: 200px; max-height: 200px" />
                }
            </td>
            <td class="align-middle">
                @Html.DisplayFor(modelItem => item.details)
            </td>
            <td class="align-middle">
                @Html.DisplayFor(modelItem => item.tblATNode.node_name)
            </td>
            <td class="align-middle">
                @Html.ActionLink("Edit", "Edit", new { id = item.plant_id }, new { @class = "btn btn-outline-info" }) 
                @Html.ActionLink("Delete", "Delete", new { id = item.plant_id }, new { @class = "btn btn-outline-danger" })
            </td>
        </tr>
    }

</table>